seed_everything: 1
trainer:
  gpus: 1
  gradient_clip_val: 0.5
  max_epochs: 600
  accumulate_grad_batches: 32
  log_every_n_steps: 5
  check_val_every_n_epoch: 10
  callbacks:
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
      init_args: 
        logging_interval: step
model:
  stepwise: true
  max_num_steps: 20
  lr: 5e-5
  warmup_steps: 1000
  model_name: t5-large
  num_beams: 10
  topk: 10
  verifier_ckpt: null
  verifier_weight: 0.0
  proof_search: false
  oracle_prover: false
  oracle_verifier: false
  diverse_beam_search: false 
  num_groups_beam_search: 5
  diversity_penalty_diverse_beam_search: 5.0
  # 'min_sp','s*min_p','s^k*min_p','s*p',
  # 'min1_sp * min2_sp',
  # 'min1_sp * min2_sp * min3_sp','min*max','min1*min2*max1*min2',
  # 'min_all_squared','min_all_cubed','multiply_all_squared','multiply_all_cubed',
  # 'min_exp_step_score','min_weight_by_stepscore','min_diff_weight_by_stepscore',
  # 'min_s_weighted','weighted_nr_ancestors','av_nr_ancestors','s'
  aggregation_method: min_sp 
  k: 2
  min_s_weighted_alpha: 1 # this is for min_s_weighted
  alpha_nr_ancestors: 0 # this is for: weighted_nr_ancestors, av_nr_ancestors
data:
  dataset: entailmentbank
  sample_goal: intermediates # hypothesis | intermediates
  subtree_proved_prob: 0.75
  subtree_proved_all_or_none: false
  batch_size: 2
  num_workers: 2
  max_input_len: 1024
  max_output_len: 64
  path_train: ../data/entailment_trees_emnlp2021_data_v3/dataset/task_2/train.jsonl
  path_val: ../data/entailment_trees_emnlp2021_data_v3/dataset/task_2/dev.jsonl
  path_test: ../data/entailment_trees_emnlp2021_data_v3/dataset/task_2/test.jsonl



        